image: ghcr.io/conda/conda-ci:gitpod-linux-python3.9
tasks:
  - init: |
      conda update -n base -c defaults conda
      conda env create -f environment.yml
      conda activate tf1
  - command: |
      python3 -m ipykernel install --user --name=python3
      for f in *.ipynb; do jupyter nbconvert --execute --to notebook --inplace "$f"; done
